import = ["/home/a00/.config/alacritty/mythemes/jellybeans.toml"]
live_config_reload = true

[cursor.style]
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "Cousine Nerd Font"
#family = "FiraCode Nerd Font"

[window]
opacity = 1.0
